---
- name: Deploy
  hosts: Portfolio
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/" # Répertoire local contenant le code
    ansistrano_deploy_to: "/home/u416463632/domains/nicolashalberstadt.com/public_html" # Répertoire distant
    # ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/after-update-code.yml"
    # ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink.yml"
    ansistrano_keep_releases: 3
  roles:
    - { role: ansistrano.deploy }